<<<<<<< HEAD
=======

>>>>>>> 9047a17277668132e52e204f25d78884ca4810c7
let names = [
  { id: '', nameTopic: 'pronouns',        name: 'pronouns' },
  { id: '', nameTopic: 'adverb',          name: 'adverb' },
  { id: '', nameTopic: 'adjective',       name: 'adjective' },
<<<<<<< HEAD
  { id: '', nameTopic: 'WFC',             name: 'words for conversition' },
=======
  { id: '', nameTopic: 'WFS',  name: 'words for speech' },
>>>>>>> 9047a17277668132e52e204f25d78884ca4810c7
  { id: '', nameTopic: 'verbs',           name: 'verbs' },
  { id: '', nameTopic: 'otherWords',      name: 'other word' }
];


let words = {
  "pronouns": [
    /********************************************/
    //           Pronouns (Местоимения)         //
    /********************************************/
    { wordEN: "i",                wordRU: "я" },
    { wordEN: "me",               wordRU: "меня, мне",                            otherTranslations: ['меня', 'мне'] },
    { wordEN: "my",               wordRU: "мой, моя, мое, мои",                   otherTranslations: ['мой', 'моя', 'мое', 'мои'] },
    { wordEN: "you",              wordRU: "ты, вы",                               otherTranslations: ['ты', 'вы'] },
    { wordEN: "you",              wordRU: "вас, вам",                             otherTranslations: ['вас', 'вам'] },
    { wordEN: "your",             wordRU: "ваш, ваше, ваши, ваша",                otherTranslations: ['ваш', 'ваше', 'ваши', 'ваша'] },
    { wordEN: "he",               wordRU: "он" },
    { wordEN: "him",              wordRU: "его, ему",                             otherTranslations: ['его', 'ему'] },
    { wordEN: "his",              wordRU: "его" },
    { wordEN: "she",              wordRU: "она" },
    { wordEN: "her",              wordRU: "её, ей",                               otherTranslations: ['её', 'ей'] },
    { wordEN: "her",              wordRU: "её" },
    { wordEN: "we",               wordRU: "мы" },
    { wordEN: "us",               wordRU: "нас, нам",                             otherTranslations: ['нас', 'нам'] },
    { wordEN: "our",              wordRU: "наш, наша, наше, наши",                otherTranslations: ['наш', 'наша', 'наше', 'наши'] },
    { wordEN: "they",             wordRU: "они" },
    { wordEN: "them",             wordRU: "их, им",                               otherTranslations: ['их', 'им'] },
    { wordEN: "their",            wordRU: "их" },
    { wordEN: "it",               wordRU: "это" },
    { wordEN: "it",               wordRU: "это, этого, этому",                    otherTranslations: ['это', 'этого', 'этому'] },
    { wordEN: "its",              wordRU: "его, её",                              otherTranslations: ['его', 'её'] },
  ],
  "adverb": [
    /********************************************/
    //       adverb (Наречие)       //
    /********************************************/
    { wordEN: "what",             wordRU: "какой? что?",                          otherTranslations: ['какой', 'что'] },
    { wordEN: "who",              wordRU: "кому? на кого? кто?",                  otherTranslations: ['кому', 'на кого', 'кто'] },
    { wordEN: "where",            wordRU: "куда? где?",                           otherTranslations: ['куда', 'где'] },
    { wordEN: "when",             wordRU: "когда?" },
    { wordEN: "why",              wordRU: "зачем? для чего? почему?",             otherTranslations: ['зачем', 'для', 'чего', 'почему'] },
    { wordEN: "how",              wordRU: "каким образом? как?",                  otherTranslations: ['каким образом', 'как'] },
    { wordEN: "whose",            wordRU: "чей? чья? чьё?",                       otherTranslations: ['чей', 'чья', 'чьё'] },
    { wordEN: "in",               wordRU: "(положение) в",                        otherTranslations: ['в'] },
    { wordEN: "to",               wordRU: "(направление) куда, к чему, к кому",   otherTranslations: ['куда', 'к чему', 'к кому'] },
    { wordEN: "from",             wordRU: "(удаление) откуда, от чего, из чего",  otherTranslations: ['откуда', 'от чего', 'из чего'] },
    { wordEN: "with",             wordRU: "с, вместе",                            otherTranslations: ['с', 'вместе'] },
    { wordEN: "over",             wordRU: "над" },
    { wordEN: "on",               wordRU: "на (поверхность предмета)",            otherTranslations: ['на'] },
    { wordEN: "by",               wordRU: "(кем?, чем?) творительный подеж",      otherTranslations: ['кем', 'чем'] },
    { wordEN: "without",          wordRU: "без" },
    { wordEN: "about",            wordRU: "о, про",                               otherTranslations: ['о', 'про'] },
    { wordEN: "for",              wordRU: "для" },
    { wordEN: "between",          wordRU: "между" },
    { wordEN: "under",            wordRU: "под" },
    { wordEN: "of",               wordRU: "(кого?, чего?) родительный падеж",     otherTranslations: ['кого', 'чего'] },
    { wordEN: "at",               wordRU: "у, возле, около, в, на",               otherTranslations: ['у', 'возле', 'около', 'в', 'на'] },
    { wordEN: "above",            wordRU: "над, выше",                            otherTranslations: ['над', 'выше'] },
    { wordEN: "as far as",        wordRU: "насколько, посколько",                 otherTranslations: ['насколько', 'посколько'] },
    { wordEN: "as for",           wordRU: "что касается" },
    { wordEN: "against",          wordRU: "напротив (против)",                    otherTranslations: ['напротив', 'против'] },
    { wordEN: "because of",       wordRU: "из-за" },
    { wordEN: "below",            wordRU: "под, ниже",                            otherTranslations: ['под', 'ниже'] },
    { wordEN: "beside",           wordRU: "рядом, с, около, возле",               otherTranslations: ['рядом', 'с', 'около', 'возле'] },
    { wordEN: "down",             wordRU: "вниз" },
    { wordEN: "inside",           wordRU: "в, внутри",                            otherTranslations: ['в', 'внутри'] },
    { wordEN: "outside",          wordRU: "снаружи, вне, за пределами",           otherTranslations: ['снаружи', 'вне', 'за пределами'] },
    { wordEN: "at all",           wordRU: "вообще, совсем",                       otherTranslations: ['вообще', 'совсем'] },
    { wordEN: "and",              wordRU: "и" },
    { wordEN: "but",              wordRU: "но" },
    { wordEN: "or",               wordRU: "или" },
    { wordEN: "if",               wordRU: "если" },
    { wordEN: "before",           wordRU: "перед тем, как",                       otherTranslations: ['перед тем'] },
    { wordEN: "after",            wordRU: "после того, как",                      otherTranslations: ['после того'] },
    { wordEN: "that",             wordRU: "что, чтобы",                           otherTranslations: ['что', 'чтобы'] },
    { wordEN: "than",             wordRU: "чем (при сравнении)",                  otherTranslations: ['чем'] }
  ],
  "adjective": [
    /********************************************/
    //       Adjective (Пригалагательные)       //
    /********************************************/
    { wordEN: "accurate",         wordRU: "точный" },
    { wordEN: "active",           wordRU: "активный" },
    { wordEN: "additional",       wordRU: "дополнительный" },
    { wordEN: "advanced",         wordRU: "передовой" },
    { wordEN: "alive",            wordRU: "живой" },
    { wordEN: "ancient",          wordRU: "древний" },
    { wordEN: "annual",           wordRU: "ежегодный" },
<<<<<<< HEAD
    { wordEN: "appropriate",      wordRU: "соответствующий" },
=======
    { wordEN: "appropirate",      wordRU: "соответствующий" },
>>>>>>> 9047a17277668132e52e204f25d78884ca4810c7
    { wordEN: "ashamed",          wordRU: "пристыженный, стыдиться" },
    { wordEN: "asleep",           wordRU: "спящий" },
    { wordEN: "attractive",       wordRU: "привлекательный" },
    { wordEN: "available",        wordRU: "доступный" },
    { wordEN: "average",          wordRU: "средний" },
    { wordEN: "awful",            wordRU: "ужасный" },
    { wordEN: "blind",            wordRU: "слепой" },
    { wordEN: "brave",            wordRU: "храбрый" },
    { wordEN: "brief",            wordRU: "короткий" },
    { wordEN: "broad",            wordRU: "широкий" },
    { wordEN: "broken",           wordRU: "сломанный" },
    { wordEN: "bitter",           wordRU: "горький" },
    { wordEN: "calm",             wordRU: "спокойный" },
    { wordEN: "careful",          wordRU: "внимательный" },
    { wordEN: "chemical",         wordRU: "химический" },
    { wordEN: "civil",            wordRU: "гражданский" },
    { wordEN: "clever",           wordRU: "умный" },
    { wordEN: "comfortable",      wordRU: "удобный" },
    { wordEN: "commercial",       wordRU: "коммерчиский" },
    { wordEN: "complex",          wordRU: "сложный" },
    { wordEN: "convenient",       wordRU: "удобный" },
    { wordEN: "cruel",            wordRU: "жестокий" },
    { wordEN: "curious",          wordRU: "интересный" },
    { wordEN: "daily",            wordRU: "ежедневный" },
    { wordEN: "dangerous",        wordRU: "опасный" },
    { wordEN: "deaf",             wordRU: "глухой" },
    { wordEN: "determined",       wordRU: "решительный" },
    { wordEN: "dirty",            wordRU: "грязный" },
    { wordEN: "distant",          wordRU: "дальний" },
    { wordEN: "domestic",         wordRU: "домашний" },
    { wordEN: "double",           wordRU: "двойной" },
    { wordEN: "dull",             wordRU: "тупой" },
    { wordEN: "eastern",          wordRU: "восточный" },
    { wordEN: "effective",        wordRU: "эффективный" },
    { wordEN: "electric",         wordRU: "электрический" },
    { wordEN: "entire",           wordRU: "целый" },
    { wordEN: "equal",            wordRU: "равный" },
    { wordEN: "essential",        wordRU: "существенный" },
    { wordEN: "exact",            wordRU: "точный" },
    { wordEN: "excellent",        wordRU: "отличный" },
    { wordEN: "extra",            wordRU: "дополнительный" },
    { wordEN: "false",            wordRU: "ложный" },
    { wordEN: "familiar",         wordRU: "знакомый" },
    { wordEN: "favourite",        wordRU: "любимый" },
    { wordEN: "following",        wordRU: "следующий" },
    { wordEN: "former",           wordRU: "бывший" },
    { wordEN: "funny",            wordRU: "смешной" },
    { wordEN: "gentle",           wordRU: "нежный" },
    { wordEN: "global",           wordRU: "глобальный" },
    { wordEN: "golden",           wordRU: "золотой" },
    { wordEN: "grand",            wordRU: "большой" },
    { wordEN: "guilty",           wordRU: "виновный" },
    { wordEN: "handsome",         wordRU: "красивый" },
    { wordEN: "healthy",          wordRU: "здоровый" },
    { wordEN: "honest",           wordRU: "честный" },
    { wordEN: "huge",             wordRU: "огромный" },
    { wordEN: "hungry",           wordRU: "голодный" },
    { wordEN: "independent",      wordRU: "независимый" },
    { wordEN: "interested",       wordRU: "интересующийся" },
    { wordEN: "internal",         wordRU: "внутренний" },
    { wordEN: "international",    wordRU: "международный" },
    { wordEN: "known",            wordRU: "известный" },
    { wordEN: "leading",          wordRU: "ведущий" },
    { wordEN: "legal",            wordRU: "законный" },
    { wordEN: "lonely",           wordRU: "одинокий" },
    { wordEN: "lost",             wordRU: "потеряный" },
    { wordEN: "loud",             wordRU: "громкий" },
    { wordEN: "lower",            wordRU: "нижний" },
    { wordEN: "lucky",            wordRU: "удачный" },
    { wordEN: "lovely",           wordRU: "прекрасный" },
    { wordEN: "mad",              wordRU: "сумасшедший" },
    { wordEN: "medical",          wordRU: "медицинский" },
    { wordEN: "medium",           wordRU: "средний" },
    { wordEN: "military",         wordRU: "военный" },
    { wordEN: "missing",          wordRU: "отсутствующий" },
    { wordEN: "modern",           wordRU: "современный" },
<<<<<<< HEAD
    { wordEN: "modest",           wordRU: "скромный" },
=======
    { wordEN: "modest",           wordRU: "скоромный" },
>>>>>>> 9047a17277668132e52e204f25d78884ca4810c7
    { wordEN: "native",           wordRU: "родной" },
    { wordEN: "negative",         wordRU: "отрицательный" },
    { wordEN: "normal",           wordRU: "нормальный" },
    { wordEN: "northern",         wordRU: "северный" },
    { wordEN: "obvious",          wordRU: "очевидный" },
    { wordEN: "ordinary",         wordRU: "обычный" },
    { wordEN: "pale",             wordRU: "бледный" },
<<<<<<< HEAD
    { wordEN: "particular",       wordRU: "особый" },
=======
    { wordEN: "particalar",       wordRU: "особый" },
>>>>>>> 9047a17277668132e52e204f25d78884ca4810c7
    { wordEN: "perfect",          wordRU: "совершенный" },
    { wordEN: "personal",         wordRU: "личный" },
    { wordEN: "physical",         wordRU: "физический" },
    { wordEN: "plain",            wordRU: "простой" },
    { wordEN: "pleasant",         wordRU: "приятный" },
    { wordEN: "pleased",          wordRU: "довольный" },
    { wordEN: "polite",           wordRU: "вежливый" },
    { wordEN: "popular",          wordRU: "популярный" },
    { wordEN: "positive",         wordRU: "положительный" },
    { wordEN: "powerful",         wordRU: "мощный" },
    { wordEN: "previous",         wordRU: "предыдущий" },
    { wordEN: "prime",            wordRU: "первый" },
<<<<<<< HEAD
    { wordEN: "professional",     wordRU: "профессиональный" },
    { wordEN: "proper",           wordRU: "правильный" },
=======
    { wordEN: "prefessional",     wordRU: "профессиональный" },
    { wordEN: "proper",           wordRU: "proper" },
>>>>>>> 9047a17277668132e52e204f25d78884ca4810c7
    { wordEN: "proud",            wordRU: "гордый" },
    { wordEN: "pure",             wordRU: "чистый" },
    { wordEN: "purple",           wordRU: "пурпурный" },
    { wordEN: "raw",              wordRU: "сырой" },
    { wordEN: "reasonable",       wordRU: "разумный" },
    { wordEN: "recent",           wordRU: "недавний" },
    { wordEN: "regular",          wordRU: "обычный" },
    { wordEN: "religious",        wordRU: "религиозный" },
    { wordEN: "reserved",         wordRU: "сдержанный" },
    { wordEN: "responsible",      wordRU: "ответственный" },
    { wordEN: "rough",            wordRU: "грубый" },
    { wordEN: "royal",            wordRU: "королевский" },
    { wordEN: "safe",             wordRU: "безопасный" },
    { wordEN: "scientific",       wordRU: "научный" },
    { wordEN: "senior",           wordRU: "старший" },
    { wordEN: "severe",           wordRU: "строгий" },
    { wordEN: "sick",             wordRU: "больной" },
    { wordEN: "significant",      wordRU: "значительный" },
    { wordEN: "silent",           wordRU: "тихий" },
    { wordEN: "similar",          wordRU: "похожий" },
    { wordEN: "smooth",           wordRU: "гладкий" },
    { wordEN: "solid",            wordRU: "твердый" },
    { wordEN: "southern",         wordRU: "южный" },
    { wordEN: "specific",         wordRU: "особый" },
    { wordEN: "steady",           wordRU: "устойчивый" },
    { wordEN: "stupid",           wordRU: "глупый" },
    { wordEN: "sudden",           wordRU: "внезапный" },
    { wordEN: "succeessful",      wordRU: "успешный" },
    { wordEN: "technical",        wordRU: "технический" },
    { wordEN: "terrible",         wordRU: "страшный" },
    { wordEN: "tight",            wordRU: "тугой" },
    { wordEN: "tired",            wordRU: "уставший" },
    { wordEN: "total",            wordRU: "суммарный" },
    { wordEN: "tough",            wordRU: "жесткий" },
    { wordEN: "traditional",      wordRU: "традиционный" },
    { wordEN: "ugly",             wordRU: "уродливый" },
    { wordEN: "unable",           wordRU: "неспособный" },
    { wordEN: "underground",      wordRU: "подземный" },
    { wordEN: "united",           wordRU: "объединенный" },
    { wordEN: "unknown",          wordRU: "неизвестный" },
    { wordEN: "unusual",          wordRU: "необычный" },
    { wordEN: "upper",            wordRU: "верхний" },
    { wordEN: "upset",            wordRU: "расстроенный" },
    { wordEN: "urgent",           wordRU: "срочный" },
    { wordEN: "useful",           wordRU: "полезный" },
    { wordEN: "valuble",          wordRU: "ценный" },
    { wordEN: "western",          wordRU: "западный" },
    { wordEN: "wet",              wordRU: "мокрый" },
    { wordEN: "wise",             wordRU: "мудрый" },
    { wordEN: "wooden",           wordRU: "деревянный" },
    { wordEN: "worth",            wordRU: "стоящий" },
    { wordEN: "worst",            wordRU: "самый плохой" }
  ],
<<<<<<< HEAD
  'WFC': [
=======
  'WFS': [
>>>>>>> 9047a17277668132e52e204f25d78884ca4810c7
    { wordEN: "abroad",           wordRU: "за границей" },
    { wordEN: "afterward",        wordRU: "позже" },
    { wordEN: "anywhere",         wordRU: "где-нибудь" },
    { wordEN: "apart",            wordRU: "в стороне" },
    { wordEN: "aside",            wordRU: "в сторону" },
    { wordEN: "badly",            wordRU: "плохо" },
    { wordEN: "carefully",        wordRU: "осторожно" },
    { wordEN: "clearly",          wordRU: "четко" },
    { wordEN: "closely",          wordRU: "близко" },
    { wordEN: "completely",       wordRU: "полностью" },
    { wordEN: "directly",         wordRU: "прямо" },
    { wordEN: "easily",           wordRU: "легко" },
    { wordEN: "entirely",         wordRU: "полностью" },
    { wordEN: "eventually",       wordRU: "в конце концов" },
    { wordEN: "everywhere",       wordRU: "везде" },
    { wordEN: "exactly",          wordRU: "точно" },
    { wordEN: "fairly",           wordRU: "достаточно" },
    { wordEN: "forever",          wordRU: "навсегда" },
    { wordEN: "frequently",       wordRU: "часто" },
    { wordEN: "generally",        wordRU: "обычно" },
    { wordEN: "hardly",           wordRU: "едва" },
    { wordEN: "highly",           wordRU: "весьма" },
    { wordEN: "immediately",      wordRU: "немедленно" },
    { wordEN: "mainly",           wordRU: "главным образом" },
    { wordEN: "meanwhile",        wordRU: "тем временем" },
    { wordEN: "mostly",           wordRU: "в основном" },
    { wordEN: "nearby",           wordRU: "рядом" },
    { wordEN: "nowadays",         wordRU: "теперь" },
    { wordEN: "nowhere",          wordRU: "нигде" },
    { wordEN: "obviously",        wordRU: "очевидно" },
    { wordEN: "otherwise",        wordRU: "иначе" },
    { wordEN: "particularly",     wordRU: "особенно" },
    { wordEN: "partly",           wordRU: "частично" },
    { wordEN: "perfectly",        wordRU: "в совершенстве" },
    { wordEN: "plenty",           wordRU: "много" },
    { wordEN: "possibly",         wordRU: "возможно" },
    { wordEN: "primarily",        wordRU: "в первую очередь" },
    { wordEN: "property",         wordRU: "правильно" },
    { wordEN: "quietly",          wordRU: "тихо" },
    { wordEN: "rapidly",          wordRU: "быстро" },
    { wordEN: "rare",             wordRU: "редко" },
    { wordEN: "recently",         wordRU: "недавно" },
    { wordEN: "seldom",           wordRU: "редко" },
    { wordEN: "simply",           wordRU: "просто" },
    { wordEN: "slightly",         wordRU: "немного" },
    { wordEN: "somehow",          wordRU: "как-нибудь" },
    { wordEN: "therefore",        wordRU: "следовательно" },
    { wordEN: "throughout",       wordRU: "везде" },
    { wordEN: "thus",             wordRU: "таким образом" },
    { wordEN: "tonight",          wordRU: "сегодня вечером" },
    { wordEN: "twice",            wordRU: "дважды" },
    { wordEN: "whatever",         wordRU: "что угожно" },
    { wordEN: "whenever",         wordRU: "когда угодно" },
    { wordEN: "unless",           wordRU: "если не" },
    { wordEN: "congratulation",   wordRU: "поздравляем" },
    { wordEN: "might",            wordRU: "может быть" },
    { wordEN: "ought",            wordRU: "должен" }
  ],
  "verbs": [
    /********************************************/
    //               Verbs (Глаголы)            //
    /********************************************/
    { wordEN: "abide",            wordRU: "обитать, пребывать" },
    { wordEN: "arise",            wordRU: "возникать, появляться" },
    { wordEN: "awake",            wordRU: "будить, просыпаться" },
    { wordEN: "accuse",           wordRU: "обвинять" },
    { wordEN: "achieve",          wordRU: "достигать" },
    { wordEN: "admit",            wordRU: "признавать" },
    { wordEN: "adopt",            wordRU: "усыновлять" },
    { wordEN: "advise",           wordRU: "советовать" },
    { wordEN: "affect",           wordRU: "влиять" },
    { wordEN: "announce",         wordRU: "объявлять" },
    { wordEN: "apologize",        wordRU: "извиняться" },
    { wordEN: "apply",            wordRU: "подавать заявление" },
    { wordEN: "approve",          wordRU: "одобрять" },
    { wordEN: "argue",            wordRU: "спорить" },
    { wordEN: "arrange",          wordRU: "устраивать" },
    { wordEN: "arrest",           wordRU: "арестовывать" },
    { wordEN: "assume",           wordRU: "предполагать" },
    { wordEN: "attend",           wordRU: "присутствовать" },
    { wordEN: "attract",          wordRU: "привлекать" },
    { wordEN: "avoid",            wordRU: "избегать" },
    { wordEN: "be",               wordRU: "быть" },
    { wordEN: "become",           wordRU: "становится" },
    { wordEN: "begin",            wordRU: "начинать" },
    { wordEN: "break",            wordRU: "сломить" },
    { wordEN: "bring",            wordRU: "приносить" },
    { wordEN: "build",            wordRU: "строить" },
    { wordEN: "buy",              wordRU: "покупать" },
    { wordEN: "bleed",            wordRU: "кровоточить" },
    { wordEN: "blow",             wordRU: "дуть" },
    { wordEN: "burn",             wordRU: "сжигать" },
    { wordEN: "bear",             wordRU: "носить, выносить" },
    { wordEN: "behold",           wordRU: "видеть, замечать" },
    { wordEN: "bereave",          wordRU: "лишать" },
    { wordEN: "beseech",          wordRU: "умолять, упрашивать" },
    { wordEN: "beset",            wordRU: "осаждать" },
    { wordEN: "bet",              wordRU: "держать пари" },
    { wordEN: "bid",              wordRU: "предлагать цену, велеть, просить" },
    { wordEN: "breed",            wordRU: "разводить (животных)" },
    { wordEN: "bust",             wordRU: "разорить(ся)" },
    { wordEN: "beat",             wordRU: "бить" },
    { wordEN: "behave",           wordRU: "вести себя" },
    { wordEN: "bend",             wordRU: "сгибать" },
    { wordEN: "bind",             wordRU: "связывать" },
    { wordEN: "bite",             wordRU: "кусать" },
    { wordEN: "blame",            wordRU: "обвинять" },
    { wordEN: "boil",             wordRU: "кипеть" },
    { wordEN: "borrow",           wordRU: "брать взаймы" },
    { wordEN: "breathe",          wordRU: "дышать" },
    { wordEN: "burst",            wordRU: "взрываться" },
    { wordEN: "bury",             wordRU: "хоронить" },
    { wordEN: "choose",           wordRU: "выбирать" },
    { wordEN: "come",             wordRU: "приходить, приезжать" },
    { wordEN: "cut",              wordRU: "резать" },
    { wordEN: "catch",            wordRU: "поймать, ловить" },
    { wordEN: "cost",             wordRU: "стоить" },
    { wordEN: "cast",             wordRU: "бросать, кидать" },
    { wordEN: "cleave",           wordRU: "рассечь" },
    { wordEN: "cling",            wordRU: "цеплять(ся)" },
    { wordEN: "close",            wordRU: "закрыть, завершить" },
    { wordEN: "clothe",           wordRU: "одеть(ся)" },
    { wordEN: "creep",            wordRU: "ползать" },
    { wordEN: "climb",            wordRU: "лезть (в верх)" },
    { wordEN: "collect",          wordRU: "собирать" },
    { wordEN: "combine",          wordRU: "сочетать" },
    { wordEN: "compare",          wordRU: "сранивать" },
    { wordEN: "complain",         wordRU: "жаловаться" },
    { wordEN: "conduct",          wordRU: "вести" },
    { wordEN: "congratulate",     wordRU: "поздравлять" },
    { wordEN: "connect",          wordRU: "подсоединить" },
    { wordEN: "consist",          wordRU: "состоять (из)" },
    { wordEN: "contain",          wordRU: "содержать" },
    { wordEN: "do",               wordRU: "делать" },
    { wordEN: "draw",             wordRU: "рисовать" },
    { wordEN: "drive",            wordRU: "водить, гнать" },
    { wordEN: "deal",             wordRU: "иметь дело" },
    { wordEN: "dream",            wordRU: "мечтать" },
    { wordEN: "drink",            wordRU: "пить" },
    { wordEN: "disprove",         wordRU: "опровергать" },
    { wordEN: "dwell",            wordRU: "обитать" },
    { wordEN: "decrease",         wordRU: "уменьшать" },
    { wordEN: "define",           wordRU: "определять" },
    { wordEN: "deliver",          wordRU: "доставлять" },
    { wordEN: "deny",             wordRU: "отрицать" },
    { wordEN: "depend",           wordRU: "зависеть" },
    { wordEN: "destroy",          wordRU: "уничтожать" },
    { wordEN: "determine",        wordRU: "определять" },
    { wordEN: "dig",              wordRU: "копать" },
    { wordEN: "disappear",        wordRU: "исчезать" },
    { wordEN: "dive",             wordRU: "нырять" },
    { wordEN: "drag",             wordRU: "тянуть" },
    { wordEN: "eat",              wordRU: "есть" },
    { wordEN: "earn",             wordRU: "зарабатывать" },
    { wordEN: "employ",           wordRU: "нанимать" },
    { wordEN: "encourage",        wordRU: "поощрять" },
    { wordEN: "escape",           wordRU: "бежать" },
    { wordEN: "establish",        wordRU: "устанавливать" },
    { wordEN: "estimate",         wordRU: "оценивать" },
    { wordEN: "examine",          wordRU: "рассматривать" },
    { wordEN: "exist",            wordRU: "существовать" },
    { wordEN: "explode",          wordRU: "взрываться" },
    { wordEN: "explore",          wordRU: "исследовать" },
    { wordEN: "express",          wordRU: "выражать" },
    { wordEN: "fall",             wordRU: "падать" },
    { wordEN: "feel",             wordRU: "чувствовать" },
    { wordEN: "find",             wordRU: "найти" },
    { wordEN: "feed",             wordRU: "кормить" },
    { wordEN: "fight",            wordRU: "бороться, сражаться" },
    { wordEN: "fly",              wordRU: "летать" },
    { wordEN: "forget",           wordRU: "забывать" },
    { wordEN: "forgive",          wordRU: "прощать" },
    { wordEN: "flee",             wordRU: "бежать, спасаться" },
    { wordEN: "fling",            wordRU: "швырять" },
    { wordEN: "forego",           wordRU: "предшествовать" },
    { wordEN: "foresee",          wordRU: "предвидеть" },
    { wordEN: "foretell",         wordRU: "предсказывать" },
    { wordEN: "forsake",          wordRU: "покидать" },
    { wordEN: "fail",             wordRU: "терпеть неудачу" },
    { wordEN: "fit",              wordRU: "быть в меру" },
    { wordEN: "fix",              wordRU: "исправлять" },
    { wordEN: "flow",             wordRU: "течь" },
    { wordEN: "focus",            wordRU: "фокусироваться" },
    { wordEN: "forbid",           wordRU: "запрещать" },
    { wordEN: "found",            wordRU: "основывать" },
    { wordEN: "freeze",           wordRU: "замерзать" },
    { wordEN: "frighten",         wordRU: "пугать" },
    { wordEN: "get",              wordRU: "получить" },
    { wordEN: "give",             wordRU: "давать" },
    { wordEN: "go",               wordRU: "идти, ехать" },
    { wordEN: "grow",             wordRU: "расти" },
    { wordEN: "grind",            wordRU: "молоть" },
    { wordEN: "glid",             wordRU: "позолотить" },
    { wordEN: "gain",             wordRU: "добывать" },
    { wordEN: "gather",           wordRU: "собирать" },
    { wordEN: "guess",            wordRU: "догадываться" },
    { wordEN: "have",             wordRU: "иметь" },
    { wordEN: "hear",             wordRU: "слышать" },
    { wordEN: "hold",             wordRU: "удерживать" },
    { wordEN: "hang",             wordRU: "висеть" },
    { wordEN: "hide",             wordRU: "скрывать" },
    { wordEN: "hit",              wordRU: "поражать, бить" },
    { wordEN: "hurt",             wordRU: "ранить, обижать, повредить" },
    { wordEN: "heave",            wordRU: "поднимать" },
    { wordEN: "hew",              wordRU: "рубить, тесать" },
    { wordEN: "handle",           wordRU: "справляться (с чем-то)" },
    { wordEN: "hate",             wordRU: "ненавидеть" },
    { wordEN: "hire",             wordRU: "нанимать" },
    { wordEN: "hope",             wordRU: "надеяться" },
    { wordEN: "hunt",             wordRU: "охотиться" },
    { wordEN: "inlay",            wordRU: "вкладывать, инкрустировать" },
    { wordEN: "input",            wordRU: "вводить (данные)" },
    { wordEN: "interweave",       wordRU: "сплетать" },
    { wordEN: "imagine",          wordRU: "представлять" },
    { wordEN: "improve",          wordRU: "улучшать" },
    { wordEN: "indicate",         wordRU: "указывать" },
    { wordEN: "infrom",           wordRU: "сообщать" },
    { wordEN: "intend",           wordRU: "намереваться" },
    { wordEN: "introduce",        wordRU: "представлять" },
    { wordEN: "invent",           wordRU: "изобретать" },
    { wordEN: "invite",           wordRU: "приглашать" },
    { wordEN: "involve",          wordRU: "привлекать" },
    { wordEN: "keep",             wordRU: "держать" },
    { wordEN: "know",             wordRU: "знать" },
    { wordEN: "kneel",            wordRU: "становиться на колени" },
    { wordEN: "knit",             wordRU: "вязать" },
    { wordEN: "kick",             wordRU: "пинать" },
    { wordEN: "knock",            wordRU: "стучать" },
    { wordEN: "leave",            wordRU: "оставлять" },
    { wordEN: "let",              wordRU: "позволять" },
    { wordEN: "lie",              wordRU: "лежать" },
    { wordEN: "lose",             wordRU: "терять" },
    { wordEN: "lay",              wordRU: "возложить" },
    { wordEN: "learn",            wordRU: "учить" },
    { wordEN: "light",            wordRU: "свет" },
    { wordEN: "leap",             wordRU: "прыгать" },
    { wordEN: "lean",             wordRU: "наклоняться" },
    { wordEN: "lend",             wordRU: "дать взаймы" },
    { wordEN: "lock",             wordRU: "закрывать (на ключ)" },
    { wordEN: "make",             wordRU: "изготавливать" },
    { wordEN: "mean",             wordRU: "означать" },
    { wordEN: "meet",             wordRU: "встречаться" },
    { wordEN: "mistake",          wordRU: "ошибаться" },
    { wordEN: "mow",              wordRU: "косить (траву)" },
    { wordEN: "maintain",         wordRU: "поддерживать" },
    { wordEN: "manage",           wordRU: "управлять" },
    { wordEN: "marry",            wordRU: "жениться" },
    { wordEN: "melt",             wordRU: "плавиться" },
    { wordEN: "mention",          wordRU: "упоминать" },
    { wordEN: "mix",              wordRU: "смешивать" },
    { wordEN: "overcome",         wordRU: "преодолевать" },
    { wordEN: "observe",          wordRU: "наблюдать" },
    { wordEN: "obtain",           wordRU: "получать" },
    { wordEN: "occupy",           wordRU: "занимать" },
    { wordEN: "occur",            wordRU: "происходить" },
    { wordEN: "organize",         wordRU: "организовывать" },
    { wordEN: "pay",              wordRU: "платить" },
    { wordEN: "put",              wordRU: "класть" },
    { wordEN: "plead",            wordRU: "заявлять" },
    { wordEN: "prove",            wordRU: "доказывать" },
    { wordEN: "perform",          wordRU: "выполнять" },
    { wordEN: "permit",           wordRU: "позволять" },
    { wordEN: "postpone",         wordRU: "откладывать" },
    { wordEN: "pour",             wordRU: "наливать" },
    { wordEN: "prefer",           wordRU: "отдавать предпочтение" },
    { wordEN: "prevent",          wordRU: "предотвращать" },
    { wordEN: "print",            wordRU: "печатать" },
    { wordEN: "propose",          wordRU: "предалагать" },
    { wordEN: "publish",          wordRU: "публиковать" },
    { wordEN: "punish",           wordRU: "наказывать" },
    { wordEN: "read",             wordRU: "читать" },
    { wordEN: "run",              wordRU: "бежать" },
    { wordEN: "ride",             wordRU: "ездить" },
    { wordEN: "ring",             wordRU: "звонить, звенеть" },
    { wordEN: "rise",             wordRU: "повышаться, подниматься" },
    { wordEN: "relay",            wordRU: "перекладывать (плитку и т.п.)" },
    { wordEN: "rid",              wordRU: "избавлять" },
    { wordEN: "realize",          wordRU: "осознавать" },
    { wordEN: "reflect",          wordRU: "отражать" },
    { wordEN: "relax",            wordRU: "расслабиться" },
    { wordEN: "release",          wordRU: "освобождать" },
    { wordEN: "remind",           wordRU: "напоминать" },
    { wordEN: "repair",           wordRU: "ремонтировать" },
    { wordEN: "replace",          wordRU: "заменять" },
    { wordEN: "require",          wordRU: "требовать" },
    { wordEN: "respond",          wordRU: "отвечать" },
    { wordEN: "reveal",           wordRU: "раскрывать" },
    { wordEN: "rub",              wordRU: "тереть" },
    { wordEN: "rush",             wordRU: "спешить" },
    { wordEN: "say",              wordRU: "сказать" },
    { wordEN: "see",              wordRU: "видеть" },
    { wordEN: "send",             wordRU: "отправлять" },
    { wordEN: "set",              wordRU: "задавать, устанавливать" },
    { wordEN: "show",             wordRU: "показывать" },
    { wordEN: "sit",              wordRU: "сидеть" },
    { wordEN: "speak",            wordRU: "говорить" },
    { wordEN: "spend",            wordRU: "проводить" },
    { wordEN: "stand",            wordRU: "стоять" },
    { wordEN: "sell",             wordRU: "продавать" },
    { wordEN: "shake",            wordRU: "трясти" },
    { wordEN: "shoot",            wordRU: "стрелять, расстрелять" },
    { wordEN: "shut",             wordRU: "закрыть" },
    { wordEN: "sing",             wordRU: "петь" },
    { wordEN: "sink",             wordRU: "потопить" },
    { wordEN: "sleep",            wordRU: "спать" },
    { wordEN: "swear",            wordRU: "поклясться, клясться, ругаться" },
    { wordEN: "swim",             wordRU: "плавать" },
    { wordEN: "saw",              wordRU: "пилить" },
    { wordEN: "sew",              wordRU: "шить" },
    { wordEN: "shear",            wordRU: "стричь" },
    { wordEN: "shed",             wordRU: "проливать (слёзы)" },
    { wordEN: "shit",             wordRU: "гадить" },
    { wordEN: "shoe",             wordRU: "обувать, подковывать" },
    { wordEN: "shrink",           wordRU: "сжиматься" },
    { wordEN: "slay",             wordRU: "убивать" },
    { wordEN: "slide",            wordRU: "скользить" },
    { wordEN: "sling",            wordRU: "швырять, подвешивать" },
    { wordEN: "slink",            wordRU: "красться" },
    { wordEN: "slit",             wordRU: "разрезать (полосами), расщеплять" },
    { wordEN: "smell",            wordRU: "пахнуть, нюхать" },
    { wordEN: "smite",            wordRU: "ударять, разбивать" },
    { wordEN: "sow",              wordRU: "сеять" },
    { wordEN: "speed",            wordRU: "мчаться" },
    { wordEN: "spell",            wordRU: "читать, писать по буквам" },
    { wordEN: "spill",            wordRU: "расплескать" },
    { wordEN: "spin",             wordRU: "прясть, вертеть" },
    { wordEN: "spit",             wordRU: "плевать" },
    { wordEN: "split",            wordRU: "расщепить(ся)" },
    { wordEN: "spoil",            wordRU: "портить" },
    { wordEN: "spring",           wordRU: "возникать, выпрыгивать" },
    { wordEN: "stick",            wordRU: "втыкать, липнуть" },
    { wordEN: "sting",            wordRU: "жалить" },
    { wordEN: "stink",            wordRU: "вонять" },
    { wordEN: "strew",            wordRU: "усеивать" },
    { wordEN: "stride",           wordRU: "шагать" },
    { wordEN: "strike",           wordRU: "ударить" },
    { wordEN: "string",           wordRU: "нанизать, натянуть" },
    { wordEN: "strive",           wordRU: "стремиться" },
    { wordEN: "sweat",            wordRU: "потеть" },
    { wordEN: "swell",            wordRU: "распахнуть" },
    { wordEN: "sail",             wordRU: "плыть" },
    { wordEN: "satisfy",          wordRU: "удовлетворять" },
    { wordEN: "search",           wordRU: "искать" },
    { wordEN: "seek",             wordRU: "искать" },
    { wordEN: "shave",            wordRU: "бриться" },
    { wordEN: "shine",            wordRU: "сиять" },
    { wordEN: "shout",            wordRU: "кричать" },
    { wordEN: "slip",             wordRU: "поскользнуться" },
    { wordEN: "solve",            wordRU: "решать" },
    { wordEN: "spread",           wordRU: "распространять" },
    { wordEN: "steal",            wordRU: "воровать" },
    { wordEN: "struggle",         wordRU: "бороться" },
    { wordEN: "succeed",          wordRU: "достигать успеха" },
    { wordEN: "suffer",           wordRU: "страдать" },
    { wordEN: "surround",         wordRU: "окружать" },
    { wordEN: "swallow",          wordRU: "глотать" },
    { wordEN: "sweep",            wordRU: "подметать" },
    { wordEN: "swing",            wordRU: "качать" },
    { wordEN: "take",             wordRU: "брать" },
    { wordEN: "tell",             wordRU: "рассказывать" },
    { wordEN: "think",            wordRU: "думать" },
    { wordEN: "teach",            wordRU: "научить, учить, преподавать" },
    { wordEN: "tear",             wordRU: "рвать, рваться" },
    { wordEN: "throw",            wordRU: "бросать" },
    { wordEN: "thrust",           wordRU: "толкать" },
    { wordEN: "tread",            wordRU: "ступать" },
    { wordEN: "threaten",         wordRU: "угрожать" },
    { wordEN: "translate",        wordRU: "переводить" },
    { wordEN: "treat",            wordRU: "лечить" },
    { wordEN: "trust",            wordRU: "доверять" },
    { wordEN: "understand",       wordRU: "понимать" },
    { wordEN: "undergo",          wordRU: "проходить, подвергаться" },
    { wordEN: "undertake",        wordRU: "предпринимать" },
    { wordEN: "undo",             wordRU: "уничтожить сделанное" },
    { wordEN: "upset",            wordRU: "опрокинуть" },
    { wordEN: "vote",             wordRU: "голосовать" },
    { wordEN: "write",            wordRU: "писать, написать" },
    { wordEN: "wear",             wordRU: "носить" },
    { wordEN: "win",              wordRU: "выигрывать, побеждать" },
    { wordEN: "weave",            wordRU: "ткать" },
    { wordEN: "wed",              wordRU: "вступать в брак" },
    { wordEN: "weep",             wordRU: "плакать" },
    { wordEN: "wet",              wordRU: "мочить" },
    { wordEN: "wind",             wordRU: "вить(ся)" },
    { wordEN: "withdraw",         wordRU: "забирать, отзывать, отказываться" },
    { wordEN: "withhold",         wordRU: "воздерживаться" },
    { wordEN: "withstand",        wordRU: "противостоять" },
    { wordEN: "wring",            wordRU: "выкручивать" },
    { wordEN: "wake",             wordRU: "просыпаться" },
    { wordEN: "waste",            wordRU: "тратить" },
    { wordEN: "whistle",          wordRU: "свистеть" },
    { wordEN: "wonder",           wordRU: "удивляться" },
  ],
  'otherWords': [
    /********************************************/
    //        Other words (Другие слова)        //
    /********************************************/
    { wordEN: "love", wordRU: "любить" },
    { wordEN: "live", wordRU: "жить" },
    { wordEN: "open", wordRU: "открыть" },
    { wordEN: "start", wordRU: "начать" },
    { wordEN: "finish", wordRU: "заканчивать" },
    { wordEN: "tomorrow", wordRU: "завтра" },
    { wordEN: "yesterday", wordRU: "вчера" },
    { wordEN: "lately", wordRU: "недавно" },
    { wordEN: "long ago", wordRU: "давно" },
    { wordEN: "home", wordRU: "дома" },
    { wordEN: "box", wordRU: "коробка" },
    { wordEN: "football", wordRU: "футбол" },
    { wordEN: "friend", wordRU: "друг" },
    { wordEN: "rose", wordRU: "роза" },
    { wordEN: "umbrella", wordRU: "зонт" },
    { wordEN: "always", wordRU: "всегда" },
    { wordEN: "today", wordRU: "сегодня" },
    { wordEN: "every day", wordRU: "каждый день" },
    { wordEN: "tonight", wordRU: "сегодня вечером" },
    { wordEN: "often", wordRU: "часто" },
    { wordEN: "never", wordRU: "никогда" },
    { wordEN: "just", wordRU: "только что" },
    { wordEN: "already", wordRU: "уже" },
    { wordEN: "usually", wordRU: "обычно" },
    { wordEN: "sometimes", wordRU: "иногда" },
    { wordEN: "ask", wordRU: "просить, спрашивать" },
    { wordEN: "answer", wordRU: "отвечать" },
    { wordEN: "talk", wordRU: "разговаривать" },
    { wordEN: "help", wordRU: "помогать" },
    { wordEN: "what?", wordRU: "что? какой?" },
    { wordEN: "who?", wordRU: "кто? кому? на кого?" },
    { wordEN: "where?", wordRU: "где? куда?" },
    { wordEN: "when?", wordRU: "когда?" },
    { wordEN: "why?", wordRU: "почему? зачем? для чего?" },
    { wordEN: "how?", wordRU: "как? каким образом?" },
    { wordEN: "whose?", wordRU: "чей? чья? чьё?" },
    { wordEN: "well", wordRU: "ну..." },
    { wordEN: "you know", wordRU: "вы знаете..." },
    { wordEN: "i mean", wordRU: "я имею ввиду..." },
    { wordEN: "sure", wordRU: "конечно, безусловно..." },
    { wordEN: "like", wordRU: "как бы, обозначает подобие..." },
    { wordEN: "sort of", wordRU: "типо того..." },
    { wordEN: "maybe", wordRU: "может быть..." },
    { wordEN: "all day", wordRU: "весь день" },
    { wordEN: "at that moment", wordRU: "в тот момент" },
    { wordEN: "at this moment", wordRU: "в данный момент" },
    { wordEN: "beautiful", wordRU: "красивый" },
    { wordEN: "believe", wordRU: "верить" },
    { wordEN: "book", wordRU: "книга" },
    { wordEN: "boyfriend", wordRU: "парень, друг" },
    { wordEN: "girlfriend", wordRU: "девушка, подруга" },
    { wordEN: "chief", wordRU: "начальник" },
    { wordEN: "children", wordRU: "дети" },
    { wordEN: "cool", wordRU: "круто, здорово" },
    { wordEN: "doubt", wordRU: "сомневаться" },
    { wordEN: "family", wordRU: "семья" },
    { wordEN: "far", wordRU: "далеко" },
    { wordEN: "food", wordRU: "еда" },
    { wordEN: "glad", wordRU: "радостный" },
    { wordEN: "happy", wordRU: "счастливый" },
    { wordEN: "house", wordRU: "дом" },
    { wordEN: "interesting", wordRU: "интересный" },
    { wordEN: "job", wordRU: "регулярная работа" },
    { wordEN: "late", wordRU: "поздно" },
    { wordEN: "midnight", wordRU: "полночь" },
    { wordEN: "name", wordRU: "имя" },
    { wordEN: "nice", wordRU: "приятно" },
    { wordEN: "noon", wordRU: "полдень" },
    { wordEN: "play", wordRU: "играть" },
    { wordEN: "scarf", wordRU: "шарф" },
    { wordEN: "solution", wordRU: "решение" },
    { wordEN: "soon", wordRU: "скоро" },
    { wordEN: "study", wordRU: "изучать (получение теор. навыков)" },
    { wordEN: "team", wordRU: "команда" },
    { wordEN: "very", wordRU: "очень" },
    { wordEN: "walk", wordRU: "гулять" },
    { wordEN: "wife", wordRU: "жена" },
    { wordEN: "work", wordRU: "работать" },
    { wordEN: "worry", wordRU: "беспокоиться" },
    { wordEN: "brightly", wordRU: "ярко" },
    { wordEN: "business trip", wordRU: "командировка" },
    { wordEN: "can't", wordRU: "не могу" },
    { wordEN: "cheap", wordRU: "дешёвый" },
    { wordEN: "countryside", wordRU: "пригород" },
    { wordEN: "delicious", wordRU: "вкусный" },
    { wordEN: "dinner", wordRU: "ужин" },
    { wordEN: "farther", wordRU: "дальше" },
    { wordEN: "foggy", wordRU: "туманный" },
    { wordEN: "gorgeous", wordRU: "великолепный" },
    { wordEN: "law", wordRU: "закон" },
    { wordEN: "meat", wordRU: "мясо" },
    { wordEN: "mind", wordRU: "возражать" },
    { wordEN: "needn't", wordRU: "не нужно" },
    { wordEN: "past", wordRU: "прошлое" },
    { wordEN: "pick", wordRU: "собирать" },
    { wordEN: "pretty", wordRU: "милая, хорошенькая" },
    { wordEN: "remember", wordRU: "помнить" },
    { wordEN: "return", wordRU: "вернуться" },
    { wordEN: "seem", wordRU: "кажется" },
    { wordEN: "skate", wordRU: "кататься на коньках" },
    { wordEN: "suit", wordRU: "подходить" },
    { wordEN: "tall", wordRU: "высокий" },
    { wordEN: "twice", wordRU: "в два раза" },
    { wordEN: "actor", wordRU: "актёр" }, ///--2
    { wordEN: "animals", wordRU: "животные" },
    { wordEN: "article", wordRU: "статья" },
    { wordEN: "bag", wordRU: "сумка" },
    { wordEN: "big", wordRU: "большой" },
    { wordEN: "brazil", wordRU: "бразилия" },
    { wordEN: "bus station", wordRU: "автобусная остановка" },
    { wordEN: "capital", wordRU: "столица" },
    { wordEN: "car", wordRU: "машина" },
    { wordEN: "cat", wordRU: "кот" },
    { wordEN: "centre", wordRU: "центр" },
    { wordEN: "coffee", wordRU: "кофе" },
    { wordEN: "colour", wordRU: "цвет" },
    { wordEN: "cup", wordRU: "чашка" },
    { wordEN: "different", wordRU: "разный" },
    { wordEN: "evening", wordRU: "вечер" },
    { wordEN: "fine", wordRU: "хорошо, прекрасно" },
    { wordEN: "flat", wordRU: "квартира" },
    { wordEN: "good", wordRU: "хороший" },
    { wordEN: "guys", wordRU: "парни" },
    { wordEN: "hospital", wordRU: "госпиталь" },
    { wordEN: "hotel", wordRU: "отель" },
    { wordEN: "ice cream", wordRU: "мороженое" },
    { wordEN: "listen", wordRU: "слушать" },
    { wordEN: "look", wordRU: "смотреть" },
    { wordEN: "marathon", wordRU: "марафон" },
    { wordEN: "morning", wordRU: "утро" },
    { wordEN: "music", wordRU: "музыка" },
    { wordEN: "new", wordRU: "новый" },
    { wordEN: "newspaper", wordRU: "газета" },
    { wordEN: "norway", wordRU: "норвегия" },
    { wordEN: "oranges", wordRU: "апельсины" },
    { wordEN: "own", wordRU: "владеть" },
    { wordEN: "people", wordRU: "люди" },
    { wordEN: "please", wordRU: "пожалуйста" },
    { wordEN: "road", wordRU: "дорога" },
    { wordEN: "sandwich", wordRU: "бутерброд" },
    { wordEN: "sky", wordRU: "небо" },
    { wordEN: "soup", wordRU: "суп" },
    { wordEN: "sports centre", wordRU: "спортивный центр" },
    { wordEN: "story", wordRU: "история" },
    { wordEN: "student", wordRU: "студент" },
    { wordEN: "sun", wordRU: "солнце" },
    { wordEN: "sunday", wordRU: "воскресенье" },
    { wordEN: "surprise", wordRU: "сюрприз" },
    { wordEN: "tasty", wordRU: "вкусный" },
    { wordEN: "tea", wordRU: "чай" },
    { wordEN: "ticket", wordRU: "билет" },
    { wordEN: "travel", wordRU: "путешествие" },
    { wordEN: "tune", wordRU: "мелодия" },
    { wordEN: "tv", wordRU: "телевизор" },
    { wordEN: "wether", wordRU: "погода" },
    { wordEN: "thanks", wordRU: "спасибо" },
    { wordEN: "row", wordRU: "ряд" },
    { wordEN: "indeed", wordRU: "действительно" },
    { wordEN: "intention", wordRU: "намерение" },
    { wordEN: "somewhere", wordRU: "где-нибудь" },
    { wordEN: "settlement", wordRU: "поселение" },
    { wordEN: "conference", wordRU: "конференция" },
    { wordEN: "connection", wordRU: "связь" },
    { wordEN: "herself", wordRU: "сама" },
    { wordEN: "universe", wordRU: "Вселенная" },
    { wordEN: "file", wordRU: "файл" },
    { wordEN: "dozen", wordRU: "дюжена" },
    { wordEN: "shade", wordRU: "тень" },
    { wordEN: "dictionary", wordRU: "словарь" },
    { wordEN: "ash", wordRU: "пепел" },
    { wordEN: "track", wordRU: "след" },
    { wordEN: "goal", wordRU: "цель" },
    { wordEN: "yard", wordRU: "двор" },
    { wordEN: "finally", wordRU: "наконец" },
    { wordEN: "bean", wordRU: "фасоль" },
    { wordEN: "trick", wordRU: "трюк" },
    { wordEN: "seed", wordRU: "семя" },
    { wordEN: "profit", wordRU: "доход" },
    { wordEN: "element", wordRU: "элемент" },
    { wordEN: "pound", wordRU: "фунт" },
    { wordEN: "pig", wordRU: "свинья" },
    { wordEN: "prison", wordRU: "тюрьма" },
    { wordEN: "gate", wordRU: "ворота" },
    { wordEN: "comb", wordRU: "расческа" },
    { wordEN: "trousers", wordRU: "брюки" },
    { wordEN: "carpet", wordRU: "ковер" },
    { wordEN: "silver", wordRU: "серебро" },
    { wordEN: "jam", wordRU: "варенье" },
    { wordEN: "presence", wordRU: "присутствие" },
    { wordEN: "property", wordRU: "собственость, свойство" },
    { wordEN: "grandson", wordRU: "внук" },
    { wordEN: "grain", wordRU: "зерно" },
    { wordEN: "sum", wordRU: "сумма" },
    { wordEN: "battle", wordRU: "битва" },
    { wordEN: "merely", wordRU: "только" },
    { wordEN: "motor", wordRU: "мотор" },
    { wordEN: "airport", wordRU: "аэропорт" },
    { wordEN: "occasion", wordRU: "случай" },
    { wordEN: "mineral", wordRU: "минерал" },
    { wordEN: "salary", wordRU: "зарплата" },
    { wordEN: "reaction", wordRU: "реакция" },
    { wordEN: "lamp", wordRU: "лампа" },
    { wordEN: "coal", wordRU: "уголь" },
    { wordEN: "band", wordRU: "группа" },
    { wordEN: "baby", wordRU: "ребенок" },
    { wordEN: "singer", wordRU: "певец" },
    { wordEN: "profession", wordRU: "профессия" },
    { wordEN: "affair", wordRU: "дело" },
    { wordEN: "expert", wordRU: "эксперт" },
    { wordEN: "fault", wordRU: "вина" },
    { wordEN: "adventure", wordRU: "приключение" },
    { wordEN: "professional", wordRU: "професиональный" },
    { wordEN: "likely", wordRU: "скорее всего" },
    { wordEN: "anyway", wordRU: "в любом случае " },
    { wordEN: "truth", wordRU: "правда" },
    { wordEN: "pressure", wordRU: "давление" },
    { wordEN: "border", wordRU: "граница" },
    { wordEN: "bow", wordRU: "лук" },
    { wordEN: "cloud", wordRU: "облако" },
    { wordEN: "sand", wordRU: "песок" },
    { wordEN: "closely", wordRU: "близко" },
    { wordEN: "appropriate", wordRU: "соответствующий" },
    { wordEN: "seldom", wordRU: "редко" },
    { wordEN: "version", wordRU: "версия" },
    { wordEN: "rare", wordRU: "редко" },
    { wordEN: "behaviour", wordRU: "поведение" },
    { wordEN: "shower", wordRU: "душ" },
    { wordEN: "pleasure", wordRU: "удовольствие" },
    { wordEN: "friendship", wordRU: "дружба" },
    { wordEN: "particularly", wordRU: "особенно" },
    { wordEN: "leather", wordRU: "кожа" },
    { wordEN: "abroad", wordRU: "за границей, везде" },
    { wordEN: "community", wordRU: "сообщество" },
    { wordEN: "itself", wordRU: "само" },
    { wordEN: "ceiling", wordRU: "потолок" },
    { wordEN: "cure", wordRU: "лекарство" },
    { wordEN: "advertisement", wordRU: "реклама" },
    { wordEN: "difficulty", wordRU: "трудности" },
    { wordEN: "spoon", wordRU: "ложка" },
    { wordEN: "religion", wordRU: "религия" },
    { wordEN: "influence", wordRU: "влияние" },
    { wordEN: "partner", wordRU: "партнер" },
    { wordEN: "meaning", wordRU: "значение" },
    { wordEN: "murder", wordRU: "убийство" },
    { wordEN: "background", wordRU: "фон" },
    { wordEN: "freedom", wordRU: "свобода" },
    { wordEN: "toy", wordRU: "игрушка" },
    { wordEN: "wing", wordRU: "крыло" },
  ]
};